server:
  port: 8080


spring:
  application:
    name: social-network

  datasource:
    url: ${DBMS_URL}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

auth:
  signer-key: ${AUTH_SIGNER_KEY}
  valid-duration: 36000 # in second
  refreshable-duration: 360000 # in second
